# application: guess-the-location
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /templates
  static_dir: templates

- url: /jobs/build_city_data
  script: main.app
  login: admin

- url: /jobs/cache_user_rankings
  script: main.app
  login: admin

- url: /jobs/send_email
  script: main.app
  login: admin

- url: /crons/build_monuments_data
  script: main.app
  login: admin

- url: /crons/email_reminder
  script: main.app
  login: admin

# - url: /jobs/build_monuments_data
#   script: main.app
#   login: admin

# - url: /crons/task_trigger
#   script: main.app
#   login: admin

- url: /jobs/playground
  script: main.app
  login: admin

- url: /_ah/spi/.*
  script: api.api

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest

- name: pycrypto
  version: latest

# - name: requests
#   version: 2.11.1

# - name: requests_toolbelt
#   version: 0.7.0